github.client-id=YOUR_CLIENT_ID
github.client-secret=YOUR_CLIENT_SECRET

quarkus.http.cors=true
quarkus.http.cors.origins=https://aleoncini.github.io
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=content-type,authorization
quarkus.http.cors.access-control-allow-credentials=true